### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [wolfeJob/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [ ] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [ ] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

Good job on this assessment Scott! This is really close to where we want you to be. We want you to make a few slight changes. One thing we wanted to see was you adding and committing the class and object files separately. So, we want you to make updates to `class_2.txt` and `class_2_example_object.txt`, but commit the changes **separately**. For class_2.txt we want you to describe what the methods do (you did this in the example object). Go ahead and make this change so that you describe which attribute the method affects. There would be no need here to name a new method such as `rennovate_method()`, because r`ennovate_room` is the method name. Sorry if this was confusing in the instructions. Then we want you to update `class_2_example_object.txt` to use the attribute examples you've said would be modified. So if we stick to the ` `rennovate_room` method, you could take the size attribute of 100 and add some number to the size method so it shows that it was altered. Do this for each method. Remember to commit the changes separately. Reach out if you have any questions about the instructions. Once you are finished send us a link to your mod_0_skills repo that has the updates, and we will take a look. Thanks Scott!

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
